# Generated by Django 4.0.4 on 2022-07-11 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RepSolic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=120, verbose_name='nombre')),
                ('Numero', models.CharField(blank=True, max_length=25, verbose_name='numero de contacto')),
                ('Direccion', models.CharField(max_length=300)),
                ('DetalleProblema', models.CharField(max_length=300, verbose_name='Detalle del problema')),
                ('ImagenProblema', models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='Imagen del problema')),
            ],
        ),
    ]
