# Generated by Django 4.0.4 on 2022-07-11 15:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repsolic',
            name='Hora',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Hora de atencion'),
            preserve_default=False,
        ),
    ]
