# Generated by Django 4.0.4 on 2022-07-11 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_repsolic_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='repsolic',
            name='Correo',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Correo'),
        ),
    ]
